#!/usr/bin/env bash
# bin/start-l2met-shuttle <command> [<argument>...]

set -eu -o pipefail

_term() {
    echo "start-l2met-shuttle: received TERM, ignoring"
}

trap _term SIGTERM

main() {
  if ! is-enabled "${L2MET_SHUTTLE_ENABLE:-1}"; then
    exec "$@"
  fi

  run-l2met-shuttle "$@"
}

run-l2met-shuttle() {
  exec "$@" 2>&1 | .heroku/l2met-shuttle/bin/l2met-shuttle -tee "${L2MET_SHUTTLE_URL:?}"
}

is-enabled() {
  (
    shopt -s extglob nocasematch
    [[ $1 == @(1|true|yes|on) ]]
  )
}

[[ "$0" != "${BASH_SOURCE[0]}" ]] || main "$@"
